A searchengine endpoint to return the available values for a key in specific container
---
tags:
  - Available values for a key in specific container
parameters:
  - name: resource_table
    in: path
    type: string
    enum: ['image', 'project', 'screen', 'well', 'plate']
    required: true
  - name: container_name
    description: The container name
    in: query
    type: string
    required: true
  - name: key
    description: the resource attribute
    in: query
    type: string
    required: true
  - name: data_source
    in: query
    type: string
    required: false
    description: If a specific data source is provided, results will be retrieved from that source. Otherwise, the default data source will be used. If no default data source is not configured, results will be gathered from all available sources.
  - name: csv
    description: a flag to return a CSV file which is created on the fly instead of JSON
    in: query
    type: boolean
    required: false

responses:
  200:
    description: A JSON contains the search results
    examples:
      results: []
